In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

### Question1: Let’s attempt to predict the survival of a horse based on various observed medical conditions. Load the data from ‘horses.csv’ and observe whether it contains missing values.

In [2]:
df = pd.read_csv('horse.csv')
pd.set_option('display.max_columns',len(df.columns))
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,nasogastric_reflux_ph,rectal_exam_feces,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,extreme_pain,absent,severe,NaN,NaN,NaN,decreased,distend_large,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,mild_pain,absent,slight,NaN,NaN,NaN,absent,other,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,mild_pain,hypomotile,none,NaN,NaN,NaN,normal,normal,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,depressed,absent,severe,none,less_1_liter,5.0,decreased,NaN,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,7.4,NaN,NaN,died,no,4300,0,0,no

In [3]:
df.shape

(299, 28)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

In [5]:
df.describe()

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
count,2.990000e+02,239.000000,275.000000,241.000000,53.000000,270.000000,266.000000,101.000000,299.000000,299.000000,299.000000
mean,1.087733e+06,38.168619,72.000000,30.460581,4.707547,46.307407,24.274436,3.039604,3659.709030,90.528428,7.387960
std,1.532032e+06,0.733744,28.646219,17.666102,1.982311,10.436743,27.364194,1.967947,5408.472421,650.637139,127.749768
min,5.184760e+05,35.400000,30.000000,8.000000,1.000000,23.000000,3.300000,0.100000,0.000000,0.000000,0.000000
25%,5.289040e+05,37.800000,48.000000,18.000000,3.000000,38.000000,6.500000,2.000000,2111.500000,0.000000,0.000000
50%,5.303010e+05,38.200000,64.000000,25.000000,5.000000,45.000000,7.500000,2.300000,2322.000000,0.000000,0.000000
75%,5.347360e+05,38.500000,88.000000,36.000000,6.500000,52.000000,56.750000,3.900000,3209.000000,0.000000,0.000000
max,5.305629e+06,40.800000,184.000000,96.000000,7.500000,75.000000,89.000000,10.100000,41110.000000,7111.000000,2209.000000

In [6]:
df.isna().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

### There are various columns with missing values

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

### Question 2: This dataset contains many categorical features, replace them with label encoding.

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols_list = ['surgery','age','temp_of_extremities','peripheral_pulse','mucous_membrane','capillary_refill_time','pain','peristalsis','abdominal_distention','nasogastric_tube','nasogastric_reflux','rectal_exam_feces','abdomen','abdomo_appearance','outcome','surgical_lesion','cp_data']
def create_labelencoder(cols_list):
    '''
    Creates Label Encoders and saves them as numpy files in (Root + LabelEncoder) path
    
    Args:
        List of dataframe columns
    '''
    for col in cols_list:
        df[col]= df[col].astype('str')
        le.fit(df[col])
        df[col] = le.transform(df[col])
        
        
create_labelencoder(cols_list)

In [9]:
df.head(20)

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,nasogastric_reflux_ph,rectal_exam_feces,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,0,0,530101,38.5,66.0,28.0,1,4,3,2,2,0,3,0,2,NaN,1,0,45.0,8.4,2,NaN,0,0,11300,0,0,0
1,1,0,534817,39.2,88.0,20.0,2,2,5,1,3,0,4,0,2,NaN,0,5,50.0,85.0,1,2.0,1,0,2208,0,0,0
2,0,0,530334,38.3,40.0,24.0,3,3,6,1,3,2,2,0,2,NaN,4,4,33.0,6.7,2,NaN,2,0,0,0,0,1
3,1,1,5290409,39.1,164.0,84.0,0,3,2,2,1,0,3,1,0,5.0,1,3,48.0,7.2,3,5.3,0,1,2208,0,0,1
4,0,0,530255,37.3,104.0,35.0,2,2,2,2,4,3,1,0,2,NaN,3,3,74.0,7.4,2,NaN,0,0,4300,0,0,0
5,0,0,528355,NaN,NaN,NaN,4,3,6,1,1,2,4,3,3,NaN,1,2,NaN,NaN,2,NaN,2,0,0,0,0,0
6,1,0,526802,37.9,48.0,16.0,3,3,4,1,3,2,0,1,3,NaN,1,0,37.0,7.0,2,NaN,2,1,3124,0,0,0
7,1,0,529607,NaN,60.0,NaN,1,2,3,1,4,0,4,3,3,NaN,1,1,44.0,8.3,2,NaN,0,1,2208,0,0,0
8,0,0,530051,NaN,80.0,36.0,1,0,6,1,5,0,3,3,3,NaN,1,0,38.0,6.2,2,NaN,1,1,3205,0,0,0
9,0,1,5299629,38.3,90.0,NaN,3,2,4,1,2,2,2,3,3,NaN,1,3,40.0,6.2,0,2.2,2,0,0,0,0,1
10,1,0,528548,38.1,66.0,12.0,1,4,1,1,3,2,2,3,3,3.0,2,0,44.0,6.0,1,3.6,2,1,2124,0,0,1
11,0,0,527927,39.1,72.0,52.0,4,2,0,1,1,1,4,1,3,NaN,0,1,50.0,7.8,2,NaN,2,1,2111,0,0,0
12,1,0,528031,37.2,42.0,12.0,4,3,4,1,3,2,0,2,3,NaN,0,0,NaN,7.0,2,NaN,2,0,4124,0,0,0
13,0,1,5291329,38.0,92.0,28.0,3,3,0,1,0,2,4,2,2,7.2,4,4,37.0,6.1,0,NaN,0,0,0,0,0,1
14,1,0,534917,38.2,76.0,28.0,1,3,4,1,3,0,2,3,0,NaN,0,1,46.0,81.0,0,2.0,2,1,2112,0,0,0
15,1,0,530233,37.6,96.0,48.0,1,3,5,1,2,2,0,3,1,4.5,0,3,45.0,6.8,2,NaN,0,1,3207,0,0,0
16,1,1,5301219,NaN,128.0,36.0,1,4,5,2,5,0,0,2,2,NaN,0,0,53.0,7.8,3,4.7,0,0,1400,0,0,1
17,0,0,526639,37.5,48.0,24.0,2,2,3,3,4,3,1,0,2,NaN,3,3,NaN,NaN,2,NaN,2,0,0,0,0,0
18,1,0,5290481,37.6,64.0,21.0,3,3,0,1,1,2,2,1,3,NaN,2,0,40.0,7.0,0,NaN,2,1,4205,0,0,1
19,0,0,532110,39.4,110.0,35.0,0,4,2,3,4,2,0,0,2,NaN,3,3,55.0,8.7,2,NaN,2,0,0,0,0,0

In [10]:
df.isna().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities        0
peripheral_pulse           0
mucous_membrane            0
capillary_refill_time      0
pain                       0
peristalsis                0
abdominal_distention       0
nasogastric_tube           0
nasogastric_reflux         0
nasogastric_reflux_ph    246
rectal_exam_feces          0
abdomen                    0
packed_cell_volume        29
total_protein             33
abdomo_appearance          0
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

### Quesion 3: Replace the missing values by the most frequent value in each column.

In [11]:
rectal_temp_median = df['rectal_temp'].median()
df['rectal_temp'].fillna(rectal_temp_median, inplace = True)

pulse_median = df['pulse'].median()
df['pulse'].fillna(pulse_median, inplace = True)

respiratory_rate_median = df['respiratory_rate'].median()
df['respiratory_rate'].fillna(respiratory_rate_median, inplace = True)

nasogastric_reflux_ph_median = df['nasogastric_reflux_ph'].median()
df['nasogastric_reflux_ph'].fillna(nasogastric_reflux_ph_median, inplace = True)

packed_cell_volume_median = df['packed_cell_volume'].median()
df['packed_cell_volume'].fillna(packed_cell_volume_median, inplace = True)

total_protein_median = df['total_protein'].median()
df['total_protein'].fillna(total_protein_median, inplace = True)

abdomo_protein_median = df['abdomo_protein'].median()
df['abdomo_protein'].fillna(abdomo_protein_median, inplace = True)

In [12]:
df.isna().sum()

surgery                  0
age                      0
hospital_number          0
rectal_temp              0
pulse                    0
respiratory_rate         0
temp_of_extremities      0
peripheral_pulse         0
mucous_membrane          0
capillary_refill_time    0
pain                     0
peristalsis              0
abdominal_distention     0
nasogastric_tube         0
nasogastric_reflux       0
nasogastric_reflux_ph    0
rectal_exam_feces        0
abdomen                  0
packed_cell_volume       0
total_protein            0
abdomo_appearance        0
abdomo_protein           0
outcome                  0
surgical_lesion          0
lesion_1                 0
lesion_2                 0
lesion_3                 0
cp_data                  0
dtype: int64

In [13]:
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,nasogastric_reflux_ph,rectal_exam_feces,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,0,0,530101,38.5,66.0,28.0,1,4,3,2,2,0,3,0,2,5.0,1,0,45.0,8.4,2,2.3,0,0,11300,0,0,0
1,1,0,534817,39.2,88.0,20.0,2,2,5,1,3,0,4,0,2,5.0,0,5,50.0,85.0,1,2.0,1,0,2208,0,0,0
2,0,0,530334,38.3,40.0,24.0,3,3,6,1,3,2,2,0,2,5.0,4,4,33.0,6.7,2,2.3,2,0,0,0,0,1
3,1,1,5290409,39.1,164.0,84.0,0,3,2,2,1,0,3,1,0,5.0,1,3,48.0,7.2,3,5.3,0,1,2208,0,0,1
4,0,0,530255,37.3,104.0,35.0,2,2,2,2,4,3,1,0,2,5.0,3,3,74.0,7.4,2,2.3,0,0,4300,0,0,0

In [14]:
X = df.drop('outcome', axis=1)
y = df['outcome']

In [15]:
from sklearn.model_selection import train_test_split

### Question 4: Fit a decision tree classifier and observe the accuracy

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [18]:
dtc = DecisionTreeClassifier()

In [19]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
dtc.score(X_train,y_train)

1.0

In [21]:
y_preds = dtc.predict(X_test)

In [22]:
dtc.score(X_test,y_test)

0.5833333333333334

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
print(accuracy_score(y_test,y_preds))

0.5833333333333334

### The accuracy of the model using decision tree classifier is 66.6%

### Question 5: Fit a random forest classifier and observe the accuracy

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rfc = RandomForestClassifier()

In [27]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [28]:
rfc.score(X_train,y_train)

1.0

In [29]:
y_preds = rfc.predict(X_test)

In [30]:
rfc.score(X_test,y_test)

0.6333333333333333

In [31]:
print(accuracy_score(y_test,y_preds))

0.6333333333333333

### The accuracy of the model using decision tree classifier is 68.3%